### ISSUE TITLE
Parse for ICD-10 diagnoses

### ISSUE THREAD

**Issue by alina-CSI** [nadavbra/ukbb_parser#2]
Hi @nadavbra,
thank you again for helping with my previous question. Working with the ukbb_parser, another two questions came up:
I would like to generate a table that looks like this in the end:
ID           T1_image_available      diabetes
12345         yes                              no
67890        no                                yes

Therefore, my questions are:
- If I use "create_ICD10_dataset" and choose T1 images as one phenotype, I get among others a series with patient IDs and row numbers ("eID") and a table "additional fields" with the information if patients received a T1 image or not and row numbers. Did I understand correctly, that the row numbers of these two files match, and that by matching the row numbers I can assign the patient ID to the information if the patient got a T1 image?
- And also, if I use "create_ICD10_dataset"  and "desired_ICD10_codes" with the ICD10 code for for example diabetes, do the numbers of the column "samples" in the ICD10_tree table match the row numbers of "eID" so that I can match these and get the IDs of patients with diabetes?

I hope, I phrased my questions not too confusingly...;) Thank you in advance and best regards
Alina

**Comment by nadavbra** [comment]
Hi Alina,

The thing to understand about the `create_ICD10_dataset` function is that the `ICD10_tree` is fundamentally different from `eid`, `additional_fields` and `covariates`. While the latter three dataframes are all indexed by sample (and therefore could easily be used with reference to one another), the `ICD10_tree` is actually indexed by ICD10 nodes, where the samples associated with each samples can be retrieved through the `samples` column (notice that it will give you indices corresponding to the Pandas index of the other dataframes/series, not the eid value of the UKB). If you want to get a sample indexed dataframe for specific ICD10 codes, you can use the `pivot_ICD10_tree_to_dataset` function.

I know this is a bit confusing, but ukbb_parser is designed like that for performance. You can see some relevant code examples in [the notebook](https://github.com/nadavbra/ukbb_parser/blob/master/ukbb_parser/ukbb_parser.py).

**Comment by alina-CSI** [comment]
Hi nadavbra,

thank you for the clarification. Could you maybe give me an example for the pivot_ICD10_tree_to_dataset function ?
To get a sample indexed dataframe, I tried among others
"pivot_ICD10_tree_to_dataset(ICD10_tree, samples_index=['samples'])" , which did not work. I am sorry if I am missing the obvious solution to the problem but I am not very experienced with python yet.
Thank you a lot for your help!

**Comment by nadavbra** [comment]
It should work something like this:
```python
sub_ICD10_tree = ICD10_tree[ICD10_tree['coding'].isin({'E66', 'C22'})] # The ICD10 codes of whatever diagnoses interest you
diagnosis_statuses_per_sample = pivot_ICD10_tree_to_dataset(sub_ICD10_tree, eid.index)
```

**Comment by alina-CSI** [comment]
Thank you, that works perfectly and does exactly what I wanted to.
