### ISSUE TITLE
create dataset error

### ISSUE THREAD

**Issue by jingali** [nadavbra/ukbb_parser#4]
For the command line, create_ukbb_phenotype_dataset --phenotype-specs-file=./phenotype_specs.py --output-dataset-file=./ukbb_dataset.csv --output-covariates-columns-file=./ukbb_covariate_columns.json
No output files can be used.
How to create the dataset by ukbb_paths.py?

**Comment by nadavbra** [comment]
What do you mean by "no output files can be used"?
Have you opened your `ukbb_paths.py` file and followed the instructions within it? Do you have access and have you downloaded all the UKB files (both the main CSV with the phenotypes, and the genetic data files)?

**Comment by jingali** [comment]
Yes, I have opened my ukbb_path.py, I don't have access to UKB files and don't know how to get them. And I tried to create the files using my own dataset, but there are so many files except phenotypic and fam files. Thus I opened the ticket before in pwas to get the related files directly.

**Comment by nadavbra** [comment]
If you don't have access to the UKB then you shouldn't use ukbb_parser. You should provide whatever phenotypic data you do have directly to the pwas package without using `create_ukbb_phenotype_dataset` (or any other ukbb_parser command). The format accepted by PWAS is very simple: just provide it with a CSV file where each row represents an individual and each column represents a phenotype or covariate you'd like to include in the analysis. If you have further questions about how to use PWAS, please ask them in the pwas GitHub repository and not here.
